#define _ELFCLIB_
#include <mathi32.h>

int32_t atoi32(const char *nptr)
{
    int32_t n;

    asm("; CDP1802 Assembly: decimal ASCII string to 32-bit signed integer");
    asm("; Compiler runtime version");
    asm(";");
    asm("; Memory layout:");
    asm(";   rb+1 .. rb+2  16-bit pointer to input string (little-endian)");
    asm(";   r7+1 .. r7+4  32-bit signed output integer (little-endian)");
    asm(";   r7-3 .. r7    scratch buffer (TMP) for multiply-by-10");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte before LSB of string pointer");
    asm(";   r7 = pointer to byte before LSB of output integer");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   [r7+1..r7+4] = parsed 32-bit signed integer");
    asm(";");
    asm("; Algorithm:");
    asm(";   result = 0");
    asm(";   for each digit d: result = result*10 + d");
    asm(";   result*10 = (result<<1) + (result<<3)");
    asm(";   Negate result if negative sign seen");
    asm(";");
    asm("; Registers:");
    asm(";   rf      input string pointer (loaded from rb+1..rb+2)");
    asm(";   ra      pointer to output integer LSB (r7+1)");
    asm(";   rc.hi   sign flag: 0=positive, 1=negative");
    asm(";   rd      pointer to TMP LSB (r7-3)");
    asm(";   r8      scratch pointer");
    asm("");
    asm("atoi32:");
    asm("        ; Load input string pointer from rb+1..rb+2 into rf");
    asm("        copy    rb, r8");
    asm("        inc     r8              ; r8 → rb+1");
    asm("");
    asm("        ldn     r8");
    asm("        plo     rf");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        phi     rf              ; rf = input string pointer");
    asm("");
    asm("        ; ra = r7+1 → output integer LSB");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; rd = r7-3 → TMP LSB");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Zero output integer");
    asm("        ldi     0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; Clear sign flag");
    asm("        ldi     0");
    asm("        phi     rc");
    asm("");
    asm("        ; --- Skip leading whitespace ---");
    asm("skipws:");
    asm("        ldn     rf");
    asm("        xri     020h            ; space?");
    asm("        lbz     skipws_adv");
    asm("        ldn     rf");
    asm("        xri     009h            ; tab?");
    asm("        lbnz    chksign");
    asm("skipws_adv:");
    asm("        inc     rf");
    asm("        lbr     skipws");
    asm("");
    asm("chksign:");
    asm("        ldn     rf");
    asm("        xri     02dh            ; '-'?");
    asm("        lbnz    chkplus");
    asm("        ldi     1");
    asm("        phi     rc");
    asm("        inc     rf");
    asm("        lbr     digitloop");
    asm("");
    asm("chkplus:");
    asm("        ldn     rf");
    asm("        xri     02bh            ; '+'?");
    asm("        lbnz    digitloop");
    asm("        inc     rf");
    asm("");
    asm("        ; --- Digit loop ---");
    asm("digitloop:");
    asm("        ldn     rf");
    asm("        smi     030h            ; D = c - '0'");
    asm("        lbnf    done            ; < '0': stop");
    asm("        smi     00ah            ; D = c - '0' - 10");
    asm("        lbdf    done            ; >= 10: stop");
    asm("        adi     00ah            ; restore digit (0-9)");
    asm("        str     r2              ; save digit in M(r2)");
    asm("        inc     rf");
    asm("");
    asm("        ; result = result * 10 + digit");
    asm("");
    asm("        ; Step 1: copy result -> TMP");
    asm("        lda     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        lda     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        lda     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     ra");
    asm("        str     rd");
    asm("");
    asm("");
    asm("        ; Restore ra and rd to LSB");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 2: result = result << 1 (result * 2)");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; Step 3: TMP = TMP << 1 (TMP = orig*2)");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 4: TMP = TMP << 1 (TMP = orig*4)");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 5: TMP = TMP << 1 (TMP = orig*8)");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 6: result = result + TMP (result*2 + result*8 = result*10)");
    asm("        sex     rd");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     ra");
    asm("        adc                     ; result[0] + TMP[0]");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        inc     rd");
    asm("");
    asm("        ldn     ra");
    asm("        adc                     ; result[1] + TMP[1] + carry");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        inc     rd");
    asm("");
    asm("        ldn     ra");
    asm("        adc                     ; result[2] + TMP[2] + carry");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        inc     rd");
    asm("");
    asm("        ldn     ra");
    asm("        adc                     ; result[3] + TMP[3] + carry");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 7: result = result + digit");
    asm("        sex     r2              ; X = r2, M(r2) = digit");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     ra");
    asm("        adc                     ; result[0] + digit");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        adci    0               ; result[1] + carry");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        adci    0               ; result[2] + carry");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        adci    0               ; result[3] + carry");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        lbr     digitloop");
    asm("");
    asm("done:");
    asm("        ; Negate result if negative");
    asm("        ghi     rc");
    asm("        lbz     rtn_done");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adi     001h");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("");
    asm("rtn_done:");

    return n;
}
