#define _ELFCLIB_
#include <mathi32.h>

int cmpi32(int32_t a, int32_t b)
{
    int r;

    asm("        ; Initialize ra = 0, rc.lo = 0 (equality accumulator)");
    asm("        ldi  0");
    asm("        plo  ra");
    asm("        phi  ra");
    asm("        plo  rc");
    asm("");
    asm("        inc  r7");
    asm("        inc  r7");
    asm("        inc  r7          ; r7 => LSB of a");
    asm("        inc  rb");
    asm("        inc  rb");
    asm("        inc  rb");
    asm("        inc  rb");
    asm("        inc  rb          ; rb => LSB of b");
    asm("");
    asm("        ; Set X = rb so sm/smb use M(rb) directly");
    asm("        sex  rb");
    asm("");
    asm("        ; --- Subtract byte 0 (LSB): D = a[0] - b[0] ---");
    asm("        lda  r7          ; D = a[0], r7 advances to byte 1");
    asm("        sm               ; D = a[0] - b[0]");
    asm("        plo  rc          ; rc.lo = diff0");
    asm("        inc  rb");
    asm("");
    asm("        ; --- Subtract byte 1 with borrow ---");
    asm("        lda  r7          ; D = a[1], r7 advances to byte 2");
    asm("        smb              ; D = a[1] - b[1] - borrow");
    asm("        str  r2          ; M(r2) = diff1");
    asm("        glo  rc");
    asm("        sex  r2");
    asm("        or               ; D = rc.lo | diff1");
    asm("        plo  rc");
    asm("        sex  rb");
    asm("        inc  rb");
    asm("");
    asm("        ; --- Subtract byte 2 with borrow ---");
    asm("        lda  r7          ; D = a[2], r7 advances to byte 3");
    asm("        smb              ; D = a[2] - b[2] - borrow");
    asm("        str  r2          ; M(r2) = diff2");
    asm("        glo  rc");
    asm("        sex  r2");
    asm("        or               ; D = rc.lo | diff2");
    asm("        plo  rc");
    asm("        sex  rb");
    asm("        inc  rb");
    asm("");
    asm("        ; --- Subtract byte 3 (MSB) with borrow ---");
    asm("        ldn  r7          ; D = a[3]");
    asm("        smb              ; D = a[3] - b[3] - borrow, final DF set");
    asm("        str  r2          ; M(r2) = diff3 (save for sign/overflow check)");
    asm("        glo  rc");
    asm("        sex  r2");
    asm("        or               ; D = rc.lo | diff3");
    asm("        lbz  done        ; all four difference bytes zero → equal");
    asm("        ldn  r2          ; restore MSB diff into D for sign/overflow check");
    asm("");
    asm("not_equal:");
    asm("        ; D = MSB difference byte, DF = final borrow");
    asm("        lbnf borrow_set");
    asm("");
    asm("no_borrow:");
    asm("        ; DF=1: a >= b unsigned");
    asm("        ; bit7=0 → no overflow → a > b → return +1");
    asm("        ; bit7=1 → overflow   → a < b → return -1");
    asm("        shl              ; bit7 → DF");
    asm("        lsnf             ; DF=0 (bit7 was 0): skip dec");
    asm("        dec  ra          ; bit7=1: overflow, a < b → ra = -1");
    asm("        skp              ; skip inc (1 byte)");
    asm("        inc  ra          ; bit7=0: no overflow, a > b → ra = +1");
    asm("        lbr  done");
    asm("borrow_set:");
    asm("        ; DF=0: a < b unsigned");
    asm("        ; bit7=1 → no overflow → a < b → return -1");
    asm("        ; bit7=0 → overflow   → a > b → return +1");
    asm("        shl              ; bit7 → DF");
    asm("        lsdf             ; DF=1 (bit7 was 1): skip inc");
    asm("        inc  ra          ; bit7=0: overflow, a > b → ra = +1");
    asm("        skp              ; skip dec (1 byte)");
    asm("        dec  ra          ; bit7=1: no overflow, a < b → ra = -1");
    asm("done:");
    asm("        dec  r7");
    asm("        dec  r7");
    asm("        dec  r7");
    asm("        dec  r7          ; r7 => MSB of r");
    asm("        ghi  ra          ; copy ra to return value");
    asm("        str  r7");
    asm("        dec  r7");
    asm("        glo  ra");
    asm("        str  r7");
    asm("        dec  r7          ; restore r7");
    asm("");
    asm("        glo  rb          ; restore rb");
    asm("        smi  8");
    asm("        plo  rb");
    asm("        ghi  rb");
    asm("        smbi 0");
    asm("        phi  rb");

    return r;
}
