#define _ELFCLIB_
#include <mathi32.h>

int32_t divi32(int32_t a, int32_t b, int32_t *rem)
{
    int32_t quotient;
    int32_t remainder;

    asm("; Branch to routine entry, skipping subroutines");
    asm("        lbr     divi32_entry");
    
    asm("; CDP1802 Assembly: 32-bit signed division for compiler runtime");
    asm(";");
    asm("; Memory layout on entry:");
    asm(";   rb+1 .. rb+4  dividend  (4 bytes, LSB first)");
    asm(";   rb+5 .. rb+8  divisor   (4 bytes, LSB first)");
    asm(";   r7+1 .. r7+4  remainder (4 bytes, output)");
    asm(";   r7+5 .. r7+8  quotient  (4 bytes, output)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte immediately before dividend LSB");
    asm(";   r7 = pointer to byte immediately before remainder LSB");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 restored to entry values");
    asm(";   [r7+1..r7+4] = signed remainder");
    asm(";   [r7+5..r7+8] = signed quotient");
    asm(";");
    asm("; The remainder has the same sign as the dividend.");
    asm("; Dividend and divisor are overwritten during computation.");
    asm(";");
    asm("; Registers used: r8, ra, rc, rd, rf");
    asm(";   ra      points to dividend LSB (rb+1)");
    asm(";   rf      points to divisor LSB  (rb+5)");
    asm(";   rd      points to remainder LSB (r7+1)");
    asm(";   r8      scratch pointer");
    asm(";   rc.lo   loop counter");
    asm(";   rc.hi   sign flags: bit1=remainder sign, bit0=quotient sign");
    asm("");
    asm("; ---------------------------------------------------------------");
    asm("; neg32: negate 32-bit little-endian value pointed to by r8");
    asm(";        single pass: invert each byte and add carry (carry starts 1)");
    asm(";        r8 must point to LSB on entry");
    asm("; ---------------------------------------------------------------");
    asm("neg32:");
    asm("        ldn     r8");
    asm("        xri     0ffh");
    asm("        adi     001h");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     r8");
    asm("");
    asm("        rtn");
    asm("");
    asm("; ---------------------------------------------------------------");
    asm("; shl32: shift 32-bit little-endian value at r8 left by 1");
    asm(";        entry: r8 → LSB, DF = bit to shift into bit0");
    asm(";        exit:  DF = old MSB bit7, r8 → LSB (restored)");
    asm("; ---------------------------------------------------------------");
    asm("shl32:");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("");
    asm("        dec     r8");
    asm("        dec     r8");
    asm("        dec     r8");
    asm("");
    asm("        rtn");
    asm("");
    asm("; ---------------------------------------------------------------");
    asm("; div32s: main entry point");
    asm("; ---------------------------------------------------------------");
    asm("divi32_entry:");
    asm("        ; ra = rb+1 → dividend LSB");
    asm("        copy    rb, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; rf = rb+5 → divisor LSB");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        ; rd = r7+1 → remainder LSB");
    asm("        copy    r7, rd");
    asm("        inc     rd");
    asm("");
    asm("        ; --- Check sign of dividend ---");
    asm("        glo     ra");
    asm("        adi     3");
    asm("        plo     r8");
    asm("        ghi     ra");
    asm("        adci    0");
    asm("        phi     r8              ; r8 → dividend MSB");
    asm("");
    asm("        ldn     r8");
    asm("        shl                     ; MSB bit7 → DF");
    asm("        ldi     0");
    asm("        phi     rc              ; rc.hi = 0");
    asm("        lbnf    dvdnd_pos");
    asm("");
    asm("        ; Dividend negative: set both sign flags, negate dividend in place");
    asm("        ldi     003h");
    asm("        phi     rc");
    asm("        copy    ra, r8");
    asm("        call    neg32");
    asm("");
    asm("dvdnd_pos:");
    asm("        ; --- Check sign of divisor ---");
    asm("        glo     rf");
    asm("        adi     3");
    asm("        plo     r8");
    asm("        ghi     rf");
    asm("        adci    0");
    asm("        phi     r8              ; r8 → divisor MSB");
    asm("");
    asm("        ldn     r8");
    asm("        shl                     ; MSB bit7 → DF");
    asm("        lbnf    divisr_pos");
    asm("");
    asm("        ; Divisor negative: toggle quotient sign, negate divisor in place");
    asm("        ghi     rc");
    asm("        xri     001h");
    asm("        phi     rc");
    asm("        copy    rf, r8");
    asm("        call    neg32");
    asm("");
    asm("divisr_pos:");
    asm("        ; --- Zero remainder (rd points to r7+1) ---");
    asm("        ldi     0");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("");
    asm("        ; --- Zero quotient (r7+5..r7+8) ---");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldi     0");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        str     r8");
    asm("");
    asm("        ; --- Shift-and-subtract loop: 32 iterations ---");
    asm("        ldi     20h");
    asm("        plo     rc");
    asm("");
    asm("divloop:");
    asm("        ; Step 1: Shift dividend left 1, old MSB → DF");
    asm("        copy    ra, r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        call    shl32           ; dividend MSB → DF");
    asm("");
    asm("        ; Step 2: Shift remainder left 1, bringing in dividend MSB at bit0");
    asm("        copy    rd, r8");
    asm("        call    shl32           ; DF from above → remainder bit0");
    asm("");
    asm("        ; Step 3: Subtract divisor from remainder (unsigned)");
    asm("        ; Branch immediately on DF before any adci can clobber it");
    asm("        copy    rd, r8");
    asm("        sex     rf");
    asm("");
    asm("        ldn     r8");
    asm("        sm                      ; rem[0] - div[0]");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        smb                     ; rem[1] - div[1] - borrow");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        smb                     ; rem[2] - div[2] - borrow");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        smb                     ; rem[3] - div[3] - borrow");
    asm("        str     r8              ; DF=1: rem>=div, DF=0: rem<div");
    asm("");
    asm("        ; Branch immediately before anything clobbers DF");
    asm("        lbnf    restore_rem");
    asm("");
    asm("        ; Step 4a: remainder >= divisor");
    asm("        ; Restore rf, reset X");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("        sex     r2");
    asm("");
    asm("        ; Shift quotient left and set bit0 = 1");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        call    shl32");
    asm("        ldn     r8");
    asm("        ori     001h");
    asm("        str     r8");
    asm("");
    asm("        lbr     next_iter");
    asm("");
    asm("restore_rem:");
    asm("        ; Step 4b: remainder < divisor - restore remainder by adding divisor back");
    asm("        ; rf is still advanced; restore it first");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        copy    rd, r8");
    asm("        sex     rf");
    asm("");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     r8");
    asm("        adc                     ; rem[0] + div[0]");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        adc                     ; rem[1] + div[1] + carry");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        adc                     ; rem[2] + div[2] + carry");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        adc                     ; rem[3] + div[3] + carry");
    asm("        str     r8");
    asm("");
    asm("        ; Restore rf, reset X");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("        sex     r2");
    asm("");
    asm("        ; Shift quotient left, bit0 = 0");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        call    shl32");
    asm("");
    asm("next_iter:");
    asm("        dec     rc");
    asm("        glo     rc");
    asm("        lbnz    divloop");
    asm("");
    asm("        ; --- Apply sign to quotient ---");
    asm("        ghi     rc");
    asm("        ani     001h");
    asm("        lbz     quot_pos");
    asm("");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        call    neg32");
    asm("");
    asm("quot_pos:");
    asm("        ; --- Apply sign to remainder ---");
    asm("        ghi     rc");
    asm("        ani     002h");
    asm("        lbz     div_done");
    asm("");
    asm("        copy    rd, r8");
    asm("        call    neg32");
    asm("");
    asm("div_done:");
  
    if (rem != NULL)
    {
        *rem = remainder;
    }
    
    return quotient;
}
