#define _ELFCLIB_
#include <mathi32.h>

char *i32toa(int32_t n, char *buffer)
{
    asm("; CDP1802 Assembly: 32-bit signed integer to decimal ASCII string");
    asm("; Compiler runtime version");
    asm(";");
    asm("; Memory layout at rb+1:");
    asm(";   rb+1 .. rb+4  32-bit signed number (little-endian, modified in place)");
    asm(";   rb+5 .. rb+6  16-bit pointer to output buffer (little-endian)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte immediately before LSB of number");
    asm(";   r7 = stack pointer; up to 11 bytes below r7 are used as digit stack");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   output buffer contains null-terminated decimal ASCII string");
    asm(";");
    asm("; div10 is inlined to avoid call/rtn disturbing r7.");
    asm(";");
    asm("; Registers:");
    asm(";   ra      pointer to number LSB (rb+1)");
    asm(";   rf      output buffer pointer");
    asm(";   rc.hi   div10 partial remainder (0..19)");
    asm(";   rc.lo   div10 bit counter (counts down from 32)");
    asm(";   rd.hi   digit count (survives across inlined div10)");
    asm(";   r8      scratch pointer");
    asm("");
    asm("        ; Load output buffer pointer from rb+5..rb+6 into rf");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     r8");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldn     r8");
    asm("        plo     rf");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        phi     rf");
    asm("");
    asm("        ; ra = rb+1 → number LSB");
    asm("        copy    rb, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; Check sign: load MSB (ra+3)");
    asm("        glo     ra");
    asm("        adi     3");
    asm("        plo     r8");
    asm("        ghi     ra");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldn     r8");
    asm("        shl                     ; bit7 → DF");
    asm("        lbnf    ita_positive");
    asm("");
    asm("        ; Negative: write '-', negate number in place");
    asm("        ldi     02dh");
    asm("        str     rf");
    asm("        inc     rf");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adi     001h");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("");
    asm("        copy    rb, ra");
    asm("        inc     ra");
    asm("");
    asm("ita_positive:");
    asm("        ; rd.hi = digit count = 0");
    asm("        ldi     0");
    asm("        phi     rd");
    asm("");
    asm("        ; --- Digit collection: inline div10, push remainder onto r7 stack ---");
    asm("digitloop:");
    asm("        ldi     0");
    asm("        phi     rc              ; partial remainder = 0");
    asm("        ldi     20h");
    asm("        plo     rc              ; 32 iterations");
    asm("");
    asm("d10loop:");
    asm("        ; Shift number left, MSB → DF");
    asm("        copy    ra, r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        shlc                    ; old MSB → DF");
    asm("        str     r8");
    asm("");
    asm("        ; partial_rem = (partial_rem << 1) | DF");
    asm("        ghi     rc");
    asm("        shlc");
    asm("        phi     rc");
    asm("");
    asm("        ; if partial_rem >= 10: subtract 10, set quotient bit");
    asm("        smi     00ah");
    asm("        lbnf    d10_lt10");
    asm("");
    asm("        phi     rc");
    asm("        ldn     ra");
    asm("        ori     001h");
    asm("        str     ra");
    asm("");
    asm("d10_lt10:");
    asm("        dec     rc");
    asm("        glo     rc");
    asm("        lbnz    d10loop");
    asm("");
    asm("        ; Push remainder (rc.hi) onto r7 stack");
    asm("        ghi     rc");
    asm("        sex     r7");
    asm("        stxd                    ; M(r7) = digit, r7--");
    asm("        sex     r2");
    asm("");
    asm("        ; Increment digit count");
    asm("        ghi     rd");
    asm("        adi     1");
    asm("        phi     rd");
    asm("");
    asm("        ; Check if number is now zero (use r8 to preserve ra)");
    asm("        copy    ra, r8");
    asm("        ldn     r8");
    asm("        lbnz    digitloop");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        lbnz    digitloop");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        lbnz    digitloop");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        lbnz    digitloop");
    asm("");
    asm("");
    asm("");
    asm("        ; --- Pop digits MSD first into output buffer ---");
    asm("        ; After N stxd: r7 = entry-N, MSD at entry-N+1 ... LSD at entry");
    asm("        ; irx steps r7 to entry-N+1 (MSD)");
    asm("        ; ldxa for all but last digit, ldx for last (leaves r7 at entry)");
    asm("");
    asm("        sex     r7");
    asm("        irx                     ; r7 → MSD");
    asm("");
    asm("poploop:");
    asm("        ghi     rd");
    asm("        smi     1");
    asm("        phi     rd              ; decrement digit count");
    asm("        lbz     last_digit");
    asm("");
    asm("        ldxa                    ; D = M(r7), r7++");
    asm("        adi     030h");
    asm("        str     rf");
    asm("        inc     rf");
    asm("        lbr     poploop");
    asm("");
    asm("last_digit:");
    asm("        ldx                     ; D = M(r7), r7 unchanged = entry value");
    asm("        adi     030h");
    asm("        str     rf");
    asm("        inc     rf");
    asm("");
    asm("        sex     r2              ; restore X = r2");
    asm("");
    asm("        ldi     0");
    asm("        str     rf              ; null terminate");

    return buffer;
}
