#define _ELFCLIB_
#include <mathi32.h>

int32_t muli32(int32_t a, int32_t b)
{
    int32_t r;
  
    asm("; ----------------------------------------------------------");
    asm("; 1.  Determine result sign: XOR of bit7 of A[3] and B[3]");
    asm(";     (byte3 is the MSB in little-endian layout)");
    asm("; ----------------------------------------------------------");
    asm("        copy r7, ra      ; copy expression stack ptr to ra");
    asm("        copy rb, rf      ; copy base ptr to rf");
    asm("        inc  rf          ; rf => LSB of a"); 
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf          ; rf => MSB of a");
    asm("        ldn  rf");
    asm("        ani  $80");
    asm("        str  r2          ; scratch = sign bit of a");
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf          ; rf => MSB of b");
    asm("        ldn  rf");
    asm("        ani  $80");
    asm("        xor              ; D = sign_a XOR sign_b");
    asm("        stxd             ; result sign => TOS");
    asm("; ----------------------------------------------------------");
    asm("; 2.  |b| in place — negate b if negative");
    asm(";     LE layout: byte0 is LSB, byte3 is MSB (sign byte).");
    asm("; ----------------------------------------------------------");
    asm("        ldn  rf          ; D = MSB of b");
    asm("        ani  $80");
    asm("        lbz  abs_a       ; skip if non-negative");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adi  1");
    asm("        str  rf");
    asm("        inc  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  rf");
    asm("        inc  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  rf");
    asm("        inc  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  rf          ; rf => MSB of b");
    asm("; ----------------------------------------------------------");
    asm("; 3.  |a| in place — negate a if negative");
    asm("; ----------------------------------------------------------");
    asm("abs_a:");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        ldn  rf          ; D = MSB of a");
    asm("        ani  $80");
    asm("        lbz  init_loop   ; skip if non-negative");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adi  1");
    asm("        str  rf");
    asm("        inc  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  rf");
    asm("        inc  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  rf");
    asm("        inc  rf");
    asm("        ldn  rf");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  rf");
    asm("init_loop:");  
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf          ; rf => MSB of b");
    asm("; ----------------------------------------------------------");
    asm("; 4.  Clear 8-byte ACC (ACC[0..7]) and set RC = 32");
    asm("; ----------------------------------------------------------");
    asm("        sex  ra");
    asm("        ldi  0");
    asm("        stxd");
    asm("        stxd");
    asm("        stxd");
    asm("        stxd");
    asm("        stxd");
    asm("        stxd");
    asm("        stxd");
    asm("        str  ra");
    asm("        copy ra, rd      ; rd => ACC");
    asm("        ldi  32");
    asm("        plo  rc");
    asm("; ----------------------------------------------------------");
    asm("; 5.  Shift-and-add loop (32 iterations)");
    asm(";     a) Shift b right 1 — LSB falls into DF");
    asm(";     b) If DF=1: ACC[0..3] += a, carry into ACC[4..7]");
    asm(";     c) Shift a left 1");
    asm(";     d) Decrement COUNT; repeat if non-zero");
    asm("; ----------------------------------------------------------");
    asm("loop:");
    asm("; 5a.  Right-shift b, LSB → DF");
    asm("        ldn  rf");
    asm("        shr");
    asm("        str  rf");
    asm("        dec  rf          ; byte3 (MSB) - DF in = 0");
    asm("        ldn  rf");
    asm("        shrc");
    asm("        str  rf");
    asm("        dec  rf          ; byte2");
    asm("        ldn  rf");
    asm("        shrc");
    asm("        str  rf");
    asm("        dec  rf          ; byte1");
    asm("        ldn  rf");
    asm("        shrc");
    asm("        str  rf          ; byte0 (LSB) - DF = old bit0");
    asm("        ; DF now = the LSB of b before shift");
    asm("        lbnf shift_a     ; if 0, skip add");
    asm("; 5b.  ACC[0..3] += a; carry propagates into ACC[4..7]");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf          ; rf => LSB of a");
    asm("        copy rd, ra      ; ra => ACC");
    asm("        lda  rf");
    asm("        add              ; D = ACC[0] + B[0], DF = carry");
    asm("        str  ra");
    asm("        inc  ra");
    asm("        lda  rf");
    asm("        adc");
    asm("        str  ra");
    asm("        inc  ra");
    asm("        lda  rf");
    asm("        adc");
    asm("        str  ra");
    asm("        inc  ra");
    asm("        lda  rf          ; rf => LSB of b");
    asm("        adc");
    asm("        str  ra");
    asm("        inc  ra          ; byte3 - ra now at ACC[4]");
    asm("        ldn  ra");
    asm("        adci 0");
    asm("        str  ra");
    asm("        inc  ra          ; ACC[4] + carry");
    asm("        ldn  ra");
    asm("        adci 0");
    asm("        str  ra");
    asm("        inc  ra          ; ACC[5]");
    asm("        ldn  ra");
    asm("        adci 0");
    asm("        str  ra");
    asm("        inc  ra          ; ACC[6]");
    asm("        ldn  ra");
    asm("        adci 0");
    asm("        str  ra          ; ACC[7]");
    asm("; 5c.  Left-shift a by 1 bit");
    asm("shift_a:");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf");
    asm("        dec  rf          ; rf => LSB of a");
    asm("        ldn  rf");
    asm("        shl");
    asm("        str  rf");
    asm("        inc  rf          ; byte0 - bit7 => DF");
    asm("        ldn  rf");
    asm("        shlc");
    asm("        str  rf");
    asm("        inc  rf          ; byte1");
    asm("        ldn  rf");
    asm("        shlc");
    asm("        str  rf");
    asm("        inc  rf          ; byte2");
    asm("        ldn  rf");
    asm("        shlc");
    asm("        str  rf          ; byte3");
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf");
    asm("        inc  rf          ; rf => MSB of b");
    asm("; 5d.  Decrement COUNT; loop if non-zero");
    asm("        dec  rc");
    asm("        glo  rc");
    asm("        lbnz loop");
    asm("; ----------------------------------------------------------");
    asm("; 6.  Apply sign");
    asm("; ----------------------------------------------------------");
    asm("        sex  r2          ; restore SP");
    asm("        irx");
    asm("        ldx              ; get sign of result");
    asm("        ani  $80");
    asm("        lbz  copy_result");
    asm("        ; Negate ACC[0..3] (low word only - we discard high word)");
    asm("        copy rd, ra      ; ra => ACC");
    asm("        ldn  ra");
    asm("        xri  $ff");
    asm("        adi  1");
    asm("        str  ra");
    asm("        inc  ra          ; byte0");
    asm("        ldn  ra");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  ra");
    asm("        inc  ra          ; byte1");
    asm("        ldn  ra");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  ra");
    asm("        inc  ra          ; byte2");
    asm("        ldn  ra");
    asm("        xri  $ff");
    asm("        adci 0");
    asm("        str  ra          ; byte3");
    asm("; ----------------------------------------------------------");
    asm("; 7.  Copy ACC[0..3] → RESULT  (forward, no re-point)");
    asm("; ----------------------------------------------------------");
    asm("copy_result:");
    asm("        inc  r7          ; r7 => LSB of result");
    asm("        lda  rd");
    asm("        str  r7");
    asm("        inc  r7          ; byte0");
    asm("        lda  rd");
    asm("        str  r7");
    asm("        inc  r7          ; byte1");
    asm("        lda  rd");
    asm("        str  r7");
    asm("        inc  r7          ; byte2");
    asm("        ldn  rd");
    asm("        str  r7          ; byte3");
    asm("        dec  r7");
    asm("        dec  r7");
    asm("        dec  r7");
    asm("        dec  r7          ; restore r7");
  
    return r;
}
