#define _ELFCLIB_
#include <mathi32.h>

int32_t strtoi32(const char *nptr, char **endptr, int base)
{
    int32_t n;

    asm("; CDP1802 Assembly: strtol - string to 32-bit signed integer");
    asm(";");
    asm("; Memory at rb+1:");
    asm(";   rb+1..rb+2  pointer to input string");
    asm(";   rb+3..rb+4  pointer to end-pointer storage (0 = ignore)");
    asm(";   rb+5        base (0=auto, 2-36)");
    asm(";");
    asm("; r7+1..r7+4   32-bit signed result (little-endian)");
    asm(";");
    asm("; Scratch below r7:");
    asm(";   r7-4..r7-1  TMP: multiply accumulator");
    asm(";   r7-6..r7-5  saved end-pointer location");
    asm(";   r7-7        saved digit value during multiply");
    asm(";");
    asm("; Entry: rb, r7 as described; Exit: rb, r7 preserved");
    asm(";");
    asm("; Registers:");
    asm(";   rf      input string pointer");
    asm(";   ra      result pointer (r7+1)");
    asm(";   r8      scratch / bit counter");
    asm(";   rc.lo   base");
    asm(";   rc.hi   sign flag");
    asm(";   rd      scratch pointer");
    asm("");
    asm("strtol:");
    asm("        ; Load string pointer → rf");
    asm("        copy    rb, r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        plo     rf");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        phi     rf");
    asm("");
    asm("        ; Load end-pointer location → save at r7-6..r7-5");
    asm("        copy    rb, r8");
    asm("        glo     r8");
    asm("        adi     3");
    asm("        plo     r8");
    asm("        ghi     r8");
    asm("        adci    0");
    asm("        phi     r8              ; r8 → rb+3");
    asm("");
    asm("        glo     r7");
    asm("        smi     6");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd              ; rd → r7-6");
    asm("");
    asm("        ldn     r8");
    asm("        str     rd");
    asm("        inc     r8");
    asm("        inc     rd");
    asm("        ldn     r8");
    asm("        str     rd              ; saved end-pointer location at r7-6..r7-5");
    asm("");
    asm("        ; Load base → rc.lo");
    asm("        copy    rb, r8");
    asm("        glo     r8");
    asm("        adi     5");
    asm("        plo     r8");
    asm("        ghi     r8");
    asm("        adci    0");
    asm("        phi     r8              ; r8 → rb+5");
    asm("        ldn     r8");
    asm("        plo     rc");
    asm("");
    asm("        ; ra = r7+1, zero result");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        ldi     0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; rc.hi = 0 (positive)");
    asm("        ldi     0");
    asm("        phi     rc");
    asm("");
    asm("        ; Skip whitespace");
    asm("skipws:");
    asm("        ldn     rf");
    asm("        xri     020h");
    asm("        lbz     skipws_adv");
    asm("        ldn     rf");
    asm("        xri     009h");
    asm("        lbnz    chksign");
    asm("skipws_adv:");
    asm("        inc     rf");
    asm("        lbr     skipws");
    asm("");
    asm("        ; Check sign");
    asm("chksign:");
    asm("        ldn     rf");
    asm("        xri     02dh");
    asm("        lbnz    chkplus");
    asm("        ldi     1");
    asm("        phi     rc");
    asm("        inc     rf");
    asm("        lbr     chkbase");
    asm("chkplus:");
    asm("        ldn     rf");
    asm("        xri     02bh");
    asm("        lbnz    chkbase");
    asm("        inc     rf");
    asm("");
    asm("        ; Determine base");
    asm("chkbase:");
    asm("        glo     rc");
    asm("        lbnz    chk16           ; non-zero base: check for 0x prefix if base=16");
    asm("");
    asm("        ; base=0: auto-detect");
    asm("        ldn     rf");
    asm("        xri     030h            ; '0'?");
    asm("        lbnz    base_dec");
    asm("");
    asm("        inc     rf");
    asm("        ldn     rf");
    asm("        xri     078h            ; 'x'?");
    asm("        lbz     base_hex");
    asm("        ldn     rf");
    asm("        xri     058h            ; 'X'?");
    asm("        lbz     base_hex");
    asm("");
    asm("        ; '0' prefix but not hex: octal");
    asm("        ldi     8");
    asm("        plo     rc");
    asm("        lbr     digitloop");
    asm("");
    asm("base_hex:");
    asm("        inc     rf");
    asm("        ldi     16");
    asm("        plo     rc");
    asm("        lbr     digitloop");
    asm("");
    asm("base_dec:");
    asm("        ldi     10");
    asm("        plo     rc");
    asm("        lbr     digitloop");
    asm("");
    asm("chk16:");
    asm("        ; If base=16, optionally skip 0x/0X prefix");
    asm("        glo     rc");
    asm("        xri     010h");
    asm("        lbnz    digitloop       ; not base 16");
    asm("");
    asm("        ldn     rf");
    asm("        xri     030h            ; '0'?");
    asm("        lbnz    digitloop");
    asm("        inc     rf");
    asm("        ldn     rf");
    asm("        xri     078h            ; 'x'?");
    asm("        lbz     skip0x");
    asm("        ldn     rf");
    asm("        xri     058h            ; 'X'?");
    asm("        lbnz    back1");
    asm("skip0x:");
    asm("        inc     rf");
    asm("        lbr     digitloop");
    asm("back1:");
    asm("        dec     rf              ; not 0x: back up over '0'");
    asm("");
    asm("        ; Main digit loop");
    asm("digitloop:");
    asm("        ldn     rf");
    asm("");
    asm("        ; Try '0'-'9': value = c - '0'");
    asm("        smi     030h");
    asm("        lbnf    done            ; < '0'");
    asm("        plo     r8              ; r8.lo = c - '0'");
    asm("        smi     00ah");
    asm("        lbnf    chk_digit       ; 0-9: r8.lo has value");
    asm("");
    asm("        ; Try 'A'-'Z': value = c - 'A' + 10");
    asm("        ldn     rf");
    asm("        smi     041h            ; D = c - 'A'");
    asm("        lbnf    try_lower       ; < 'A'");
    asm("        smi     01ah            ; D = c - 'A' - 26");
    asm("        lbdf    try_lower       ; >= 26: not A-Z");
    asm("        adi     01ah            ; restore: D = c - 'A'");
    asm("        adi     00ah            ; D = c - 'A' + 10");
    asm("        plo     r8");
    asm("        lbr     chk_digit");
    asm("");
    asm("try_lower:");
    asm("        ; Try 'a'-'z': value = c - 'a' + 10");
    asm("        ldn     rf");
    asm("        smi     061h            ; D = c - 'a'");
    asm("        lbnf    done            ; < 'a'");
    asm("        smi     01ah            ; D = c - 'a' - 26");
    asm("        lbdf    done            ; >= 26: not a-z");
    asm("        adi     01ah            ; restore: D = c - 'a'");
    asm("        adi     00ah            ; D = c - 'a' + 10");
    asm("        plo     r8");
    asm("");
    asm("");
    asm("chk_digit:");
    asm("        ; Check digit value < base");
    asm("        glo     r8              ; digit value");
    asm("        str     r2              ; M(r2) = digit");
    asm("        glo     rc              ; base");
    asm("        sd                      ; D = M(r2) - D = digit - base");
    asm("        lbdf    done            ; digit >= base: stop");
    asm("");
    asm("        ; Valid digit: advance rf");
    asm("        inc     rf");
    asm("");
    asm("        ; Save digit at r7-7");
    asm("        glo     r7");
    asm("        smi     7");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("        glo     r8");
    asm("        str     rd");
    asm("");
    asm("        ; Multiply result by base using shift-and-add");
    asm("        ; Zero TMP at r7-4..r7-1");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("        ldi     0");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("");
    asm("        ; Load base into r8.hi, shift left 2 to align MSB to bit7");
    asm("        ; (base <= 36 < 64, so 6 bits needed)");
    asm("        glo     rc");
    asm("        shl");
    asm("        shl");
    asm("        phi     r8");
    asm("");
    asm("        ldi     6");
    asm("        plo     r8              ; 6 iterations");
    asm("");
    asm("mulloop:");
    asm("        ; TMP = TMP << 1");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("");
    asm("        ; Extract next base bit (MSB first)");
    asm("        ghi     r8");
    asm("        shl                     ; bit7 → DF");
    asm("        phi     r8");
    asm("        lbnf    mul_skip        ; bit=0: skip add");
    asm("");
    asm("        ; TMP = TMP + result");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        sex     ra");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        sex     r2");
    asm("");
    asm("mul_skip:");
    asm("        dec     r8");
    asm("        glo     r8");
    asm("        lbnz    mulloop");
    asm("");
    asm("        ; result = TMP");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        lda     rd");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        lda     rd");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        lda     rd");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; result = result + digit");
    asm("        glo     r7");
    asm("        smi     7");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("        ldn     rd");
    asm("        str     r2              ; M(r2) = digit");
    asm("");
    asm("        sex     r2");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     ra");
    asm("        adc                     ; result[0] + digit");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        lbr     digitloop");
    asm("");
    asm("done:");
    asm("        ; Apply sign");
    asm("        ghi     rc");
    asm("        lbz     store_endp");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adi     001h");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        xri     0ffh");
    asm("        adci    0");
    asm("        str     ra");
    asm("");
    asm("store_endp:");
    asm("        ; Load saved end-pointer location from r7-6..r7-5");
    asm("        glo     r7");
    asm("        smi     6");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ldn     rd");
    asm("        plo     ra");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        phi     ra              ; ra = end-pointer location");
    asm("");
    asm("        ; If zero, skip");
    asm("        glo     ra");
    asm("        lbnz    write_endp");
    asm("        ghi     ra");
    asm("        lbz     rtn_done");
    asm("");
    asm("write_endp:");
    asm("        ; Store rf at location pointed to by ra");
    asm("        glo     rf");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ghi     rf");
    asm("        str     ra");
    asm("");
    asm("rtn_done:");

    return n;
}
