#define _ELFCLIB_
#include <math32.h>

int cmpi32(int32_t a, int32_t b)
{
    int r;

    asm("; CDP1802 Assembly: compare two 32-bit signed numbers, compiler runtime");
    asm(";");
    asm("; Memory layout at rb+1:");
    asm(";   rb+1 .. rb+4  a (4 bytes, LSB first)");
    asm(";   rb+5 .. rb+8  b (4 bytes, LSB first)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte immediately before LSB of a");
    asm(";   r7 = pointer to byte immediately before result LSB");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   [r7+1..r7+2] = 0x0000 if a == b");
    asm(";                  0x0001 if a >  b");
    asm(";                  0xFFFF if a <  b  (16-bit signed -1)");
    asm(";");
    asm("; Registers: r8, ra, rc, rd, rf");
    asm(";   ra      result accumulator (0, then inc=+1 or dec=-1)");
    asm(";   r8.lo   saved MSB of a");
    asm(";   rc.lo   saved MSB of b / equality OR accumulator");
    asm(";   rd      walks through a / b during subtraction");
    asm(";   rf      walks through b during subtraction");
    asm("");
    asm("cmp32:");
    asm("        ; Initialize result accumulator ra = 0");
    asm("        ldi     0");
    asm("        plo     ra");
    asm("        phi     ra");
    asm("");
    asm("        ; Load MSB of a from rb+4");
    asm("        glo     rb");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldn     r8");
    asm("        plo     r8              ; r8.lo = a MSB");
    asm("");
    asm("        ; Load MSB of b from rb+8");
    asm("        glo     rb");
    asm("        adi     8");
    asm("        plo     rd");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rd");
    asm("        ldn     rd");
    asm("        plo     rc              ; rc.lo = b MSB");
    asm("");
    asm("        ; Check sign of a");
    asm("        glo     r8");
    asm("        shl                     ; a sign bit → DF");
    asm("        lbnf    a_pos");
    asm("");
    asm("a_neg:");
    asm("        ; a negative: check sign of b");
    asm("        glo     rc");
    asm("        shl                     ; b sign bit → DF");
    asm("        lbnf    ret_neg         ; b positive: a < b");
    asm("        lbr     same_sign       ; both negative");
    asm("");
    asm("a_pos:");
    asm("        ; a positive: check sign of b");
    asm("        glo     rc");
    asm("        shl                     ; b sign bit → DF");
    asm("        lbdf    ret_pos         ; b negative: a > b");
    asm("                                ; both positive: fall through");
    asm("");
    asm("same_sign:");
    asm("        ; rd = rb+1 → a LSB");
    asm("        copy    rb, rd");
    asm("        inc     rd");
    asm("");
    asm("        ; rf = rb+5 → b LSB");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        ldi     0");
    asm("        plo     rc              ; equality OR = 0");
    asm("");
    asm("        sex     rf");
    asm("");
    asm("        lda     rd");
    asm("        sm                      ; a[0] - b[0]");
    asm("        plo     rc");
    asm("        inc     rf");
    asm("");
    asm("        lda     rd");
    asm("        smb                     ; a[1] - b[1] - borrow");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sex     r2");
    asm("        or");
    asm("        plo     rc");
    asm("        sex     rf");
    asm("        inc     rf");
    asm("");
    asm("        lda     rd");
    asm("        smb                     ; a[2] - b[2] - borrow");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sex     r2");
    asm("        or");
    asm("        plo     rc");
    asm("        sex     rf");
    asm("        inc     rf");
    asm("");
    asm("        ldn     rd");
    asm("        smb                     ; a[3] - b[3] - borrow, final DF");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sex     r2");
    asm("        or                      ; final equality OR");
    asm("        sex     r2");
    asm("");
    asm("        lbz     ret_equal       ; all differences zero: a == b");
    asm("        lbnf    ret_neg         ; borrow: a < b");
    asm("");
    asm("ret_pos:");
    asm("        inc     ra              ; ra = 0x0001");
    asm("        lbr     store");
    asm("");
    asm("ret_neg:");
    asm("        dec     ra              ; ra = 0xFFFF");
    asm("        lbr     store");
    asm("");
    asm("ret_equal:");
    asm("                                ; ra already 0x0000");
    asm("");
    asm("store:");
    asm("        ; Write ra as 16-bit little-endian to r7+1..r7+2");
    asm("        glo     r7");
    asm("        adi     1");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        adci    0");
    asm("        phi     rd              ; rd = r7+1");
    asm("");
    asm("        glo     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ghi     ra");
    asm("        str     rd");

    return r;
}
