#define _ELFCLIB_
#include <math32.h>

uint32_t divu32(uint32_t a, uint32_t b, uint32_t *rem)
{
    uint32_t quotient;
    uint32_t remainder;

    asm("; Branch to routine entry, skipping subroutines");
    asm("        lbr     divu32_entry");
    
    asm("; CDP1802 Assembly: unsigned 32-bit division for compiler runtime");
    asm(";");
    asm("; Memory layout on entry:");
    asm(";   rb+1 .. rb+4  dividend  (4 bytes, LSB first)");
    asm(";   rb+5 .. rb+8  divisor   (4 bytes, LSB first)");
    asm(";   r7+1 .. r7+4  remainder (4 bytes, output)");
    asm(";   r7+5 .. r7+8  quotient  (4 bytes, output)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte immediately before dividend LSB");
    asm(";   r7 = pointer to byte immediately before remainder LSB");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   [r7+1..r7+4] = unsigned remainder");
    asm(";   [r7+5..r7+8] = unsigned quotient");
    asm(";");
    asm("; Registers used: r8, ra, rc, rd, rf");
    asm(";   ra      points to dividend LSB (rb+1); quotient builds here in place");
    asm(";   rf      points to divisor LSB  (rb+5)");
    asm(";   rd      points to remainder LSB (r7+1)");
    asm(";   r8      scratch pointer");
    asm(";   rc.lo   loop counter");
    asm("");
    asm("; ---------------------------------------------------------------");
    asm("; shl32: shift 32-bit little-endian value at r8 left by 1");
    asm(";        entry: r8 → LSB, DF = bit to shift into bit0");
    asm(";        exit:  DF = old MSB bit7, r8 → LSB (restored)");
    asm("; ---------------------------------------------------------------");
    asm("shl32:");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("");
    asm("        dec     r8");
    asm("        dec     r8");
    asm("        dec     r8");
    asm("");
    asm("        rtn");
    asm("");
    asm("; ---------------------------------------------------------------");
    asm("; divu32: main entry point");
    asm("; ---------------------------------------------------------------");
    asm("divu32_entry:");
    asm("        ; ra = rb+1 → dividend LSB");
    asm("        copy    rb, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; rf = rb+5 → divisor LSB");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        ; rd = r7+1 → remainder LSB");
    asm("        copy    r7, rd");
    asm("        inc     rd");
    asm("");
    asm("");
    asm("        ; --- Zero remainder ---");
    asm("        ldi     0");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("");
    asm("        ; --- Zero quotient (r7+5..r7+8) ---");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldi     0");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        str     r8");
    asm("");
    asm("        ; --- Shift-and-subtract loop: 32 iterations ---");
    asm("        ldi     20h");
    asm("        plo     rc");
    asm("");
    asm("divloop:");
    asm("        ; Shift dividend left 1, old MSB → DF");
    asm("        copy    ra, r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        call    shl32           ; dividend MSB → DF");
    asm("");
    asm("        ; Shift remainder left 1, bringing in dividend MSB at bit0");
    asm("        copy    rd, r8");
    asm("        call    shl32");
    asm("");
    asm("        ; Subtract divisor from remainder; branch before DF is clobbered");
    asm("        copy    rd, r8");
    asm("        sex     rf");
    asm("");
    asm("        ldn     r8");
    asm("        sm                      ; rem[0] - div[0]");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        smb                     ; rem[1] - div[1] - borrow");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        smb                     ; rem[2] - div[2] - borrow");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        smb                     ; rem[3] - div[3] - borrow");
    asm("        str     r8");
    asm("");
    asm("        lbnf    restore_rem     ; DF=0: rem < divisor");
    asm("");
    asm("        ; Remainder >= divisor: restore rf, shift 1 into quotient");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("        sex     r2");
    asm("");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        call    shl32");
    asm("        ldn     r8");
    asm("        ori     001h");
    asm("        str     r8");
    asm("");
    asm("        lbr     next_iter");
    asm("");
    asm("restore_rem:");
    asm("        ; Restore rf");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        ; Add divisor back to remainder");
    asm("        copy    rd, r8");
    asm("        sex     rf");
    asm("");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("");
    asm("        ldn     r8");
    asm("        adc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        adc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        adc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        inc     rf");
    asm("");
    asm("        ldn     r8");
    asm("        adc");
    asm("        str     r8");
    asm("");
    asm("        ; Restore rf, reset X");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("        sex     r2");
    asm("");
    asm("        ; Shift 0 into quotient");
    asm("        glo     rd");
    asm("        adi     4");
    asm("        plo     r8");
    asm("        ghi     rd");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldi     0");
    asm("        shr                     ; DF = 0");
    asm("        call    shl32");
    asm("");
    asm("next_iter:");
    asm("        dec     rc");
    asm("        glo     rc");
    asm("        lbnz    divloop");
    asm("");
    asm("        ; Copy quotient (r7+5..r7+8) to result");
    asm("        ; Quotient was built in separate buffer at rd+4; no copy needed");
    asm("        ; Remainder is already at rd (r7+1..r7+4)");
    asm("");
  
    if (rem != NULL)
    {
        *rem = remainder;
    }
    
    return quotient;
}
