#define _ELFCLIB_
#include <math32.h>

uint32_t mulu32x16(uint32_t a, unsigned int b)
{
    uint32_t r;

    asm("; CDP1802 Assembly: 32-bit x 16-bit unsigned multiplication");
    asm(";");
    asm("; Memory layout on entry:");
    asm(";   rb+1 .. rb+4  32-bit multiplicand (LSB first, modified in place)");
    asm(";   rb+5 .. rb+6  16-bit multiplier   (LSB first, modified in place)");
    asm(";");
    asm("; r7+1 .. r7+4   32-bit unsigned result (lower 32 bits of product)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte immediately before multiplicand LSB");
    asm(";   r7 = pointer to byte immediately before result LSB");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   [r7+1..r7+4] = lower 32 bits of product");
    asm(";");
    asm("; Registers:");
    asm(";   ra      pointer to multiplicand LSB (rb+1)");
    asm(";   rf      pointer to multiplier LSB   (rb+5)");
    asm(";   rd      pointer to result LSB       (r7+1)");
    asm(";   r8      scratch pointer");
    asm(";   rc.lo   loop counter");
    asm("");
    asm("umul32x16:");
    asm("        ; ra = rb+1 → multiplicand LSB");
    asm("        copy    rb, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; rf = rb+5 → multiplier LSB");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        ; rd = r7+1 → result LSB");
    asm("        copy    r7, rd");
    asm("        inc     rd");
    asm("");
    asm("        ; Zero result");
    asm("        ldi     0");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("");
    asm("        ldi     10h");
    asm("        plo     rc              ; 16 iterations");
    asm("");
    asm("mulloop:");
    asm("        ; Shift multiplier right 1 MSB first; old LSB → DF");
    asm("        glo     rf");
    asm("        adi     1");
    asm("        plo     r8");
    asm("        ghi     rf");
    asm("        adci    0");
    asm("        phi     r8              ; r8 → multiplier MSB (rb+6)");
    asm("");
    asm("        ldn     r8");
    asm("        shr                     ; MSB: 0 → bit7, bit0 → DF");
    asm("        str     r8");
    asm("        dec     r8");
    asm("        ldn     r8");
    asm("        shrc                    ; LSB: old bit0 → DF");
    asm("        str     r8");
    asm("");
    asm("        lbnf    no_add          ; multiplier bit was 0: skip add");
    asm("");
    asm("        ; Add multiplicand to result");
    asm("        copy    ra, r8          ; r8 → multiplicand LSB");
    asm("");
    asm("        ldn     r8");
    asm("        str     r2");
    asm("        ldn     rd");
    asm("        sex     r2");
    asm("        add                     ; result[0] + multiplicand[0]");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        str     r2");
    asm("        ldn     rd");
    asm("        adc                     ; + carry");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        str     r2");
    asm("        ldn     rd");
    asm("        adc                     ; + carry");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     r8");
    asm("");
    asm("        ldn     r8");
    asm("        str     r2");
    asm("        ldn     rd");
    asm("        adc                     ; + carry");
    asm("        str     rd");
    asm("");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("        dec     rd");
    asm("");
    asm("        sex     r2");
    asm("");
    asm("no_add:");
    asm("        ; Shift multiplicand left 1 LSB first");
    asm("        copy    ra, r8");
    asm("");
    asm("        ldn     r8");
    asm("        shl");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        shlc");
    asm("        str     r8");
    asm("");
    asm("        dec     rc");
    asm("        glo     rc");
    asm("        lbnz    mulloop");

    return r;
}
