#define _ELFCLIB_
#include <math32.h>

uint32_t strtou32(const char *nptr, char **endptr, int base)
{
    uint32_t n;

    asm("; CDP1802 Assembly: unsigned strtoul - string to unsigned 32-bit integer");
    asm("; Compiler runtime version");
    asm(";");
    asm("; Memory at rb+1:");
    asm(";   rb+1..rb+2  pointer to input string");
    asm(";   rb+3..rb+4  pointer to end-pointer storage (0 = ignore)");
    asm(";   rb+5        base (0=auto, 2-36)");
    asm(";");
    asm("; r7+1..r7+4   32-bit unsigned result (little-endian)");
    asm(";");
    asm("; Scratch below r7:");
    asm(";   r7-4..r7-1  TMP: multiply accumulator");
    asm(";   r7-6..r7-5  saved end-pointer location");
    asm(";   r7-7        saved digit value during multiply");
    asm(";");
    asm("; Entry: rb, r7 as described; Exit: rb, r7 preserved");
    asm(";");
    asm("; Registers:");
    asm(";   rf      input string pointer");
    asm(";   ra      result pointer (r7+1)");
    asm(";   r8      scratch");
    asm(";   rc.lo   base");
    asm(";   rc.hi   scratch (multiply bit counter)");
    asm(";   rd      scratch pointer");
    asm("");
    asm("strtou32:");
    asm("        ; Load string pointer → rf");
    asm("        copy    rb, r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        plo     rf");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        phi     rf");
    asm("");
    asm("        ; Save end-pointer location at r7-6..r7-5");
    asm("        copy    rb, r8");
    asm("        glo     r8");
    asm("        adi     3");
    asm("        plo     r8");
    asm("        ghi     r8");
    asm("        adci    0");
    asm("        phi     r8");
    asm("");
    asm("        glo     r7");
    asm("        smi     6");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ldn     r8");
    asm("        str     rd");
    asm("        inc     r8");
    asm("        inc     rd");
    asm("        ldn     r8");
    asm("        str     rd");
    asm("");
    asm("        ; Load base → rc.lo");
    asm("        copy    rb, r8");
    asm("        glo     r8");
    asm("        adi     5");
    asm("        plo     r8");
    asm("        ghi     r8");
    asm("        adci    0");
    asm("        phi     r8");
    asm("        ldn     r8");
    asm("        plo     rc");
    asm("");
    asm("        ; ra = r7+1, zero result");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        ldi     0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; Skip whitespace");
    asm("skipws:");
    asm("        ldn     rf");
    asm("        xri     020h");
    asm("        lbz     skipws_adv");
    asm("        ldn     rf");
    asm("        xri     009h");
    asm("        lbnz    chkplus");
    asm("skipws_adv:");
    asm("        inc     rf");
    asm("        lbr     skipws");
    asm("");
    asm("        ; Allow optional '+' prefix (no '-' for unsigned)");
    asm("chkplus:");
    asm("        ldn     rf");
    asm("        xri     02bh");
    asm("        lbnz    chkbase");
    asm("        inc     rf");
    asm("");
    asm("        ; Determine base");
    asm("chkbase:");
    asm("        glo     rc");
    asm("        lbnz    chk16");
    asm("");
    asm("        ; base=0: auto-detect");
    asm("        ldn     rf");
    asm("        xri     030h");
    asm("        lbnz    base_dec");
    asm("");
    asm("        inc     rf");
    asm("        ldn     rf");
    asm("        xri     078h");
    asm("        lbz     base_hex");
    asm("        ldn     rf");
    asm("        xri     058h");
    asm("        lbz     base_hex");
    asm("");
    asm("        ldi     8");
    asm("        plo     rc");
    asm("        lbr     digitloop");
    asm("");
    asm("base_hex:");
    asm("        inc     rf");
    asm("        ldi     16");
    asm("        plo     rc");
    asm("        lbr     digitloop");
    asm("");
    asm("base_dec:");
    asm("        ldi     10");
    asm("        plo     rc");
    asm("        lbr     digitloop");
    asm("");
    asm("chk16:");
    asm("        glo     rc");
    asm("        xri     010h");
    asm("        lbnz    digitloop");
    asm("");
    asm("        ldn     rf");
    asm("        xri     030h");
    asm("        lbnz    digitloop");
    asm("        inc     rf");
    asm("        ldn     rf");
    asm("        xri     078h");
    asm("        lbz     skip0x");
    asm("        ldn     rf");
    asm("        xri     058h");
    asm("        lbnz    back1");
    asm("skip0x:");
    asm("        inc     rf");
    asm("        lbr     digitloop");
    asm("back1:");
    asm("        dec     rf");
    asm("");
    asm("digitloop:");
    asm("        ldn     rf");
    asm("");
    asm("        ; '0'-'9'");
    asm("        smi     030h");
    asm("        lbnf    done");
    asm("        plo     r8");
    asm("        smi     00ah");
    asm("        lbnf    chk_digit");
    asm("");
    asm("        ; 'A'-'Z'");
    asm("        ldn     rf");
    asm("        smi     041h");
    asm("        lbnf    try_lower");
    asm("        smi     01ah");
    asm("        lbdf    try_lower");
    asm("        adi     01ah");
    asm("        adi     00ah");
    asm("        plo     r8");
    asm("        lbr     chk_digit");
    asm("");
    asm("try_lower:");
    asm("        ; 'a'-'z'");
    asm("        ldn     rf");
    asm("        smi     061h");
    asm("        lbnf    done");
    asm("        smi     01ah");
    asm("        lbdf    done");
    asm("        adi     01ah");
    asm("        adi     00ah");
    asm("        plo     r8");
    asm("");
    asm("chk_digit:");
    asm("        glo     r8");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sd                      ; digit - base, DF=0 if digit < base");
    asm("        lbdf    done");
    asm("");
    asm("        inc     rf");
    asm("");
    asm("        ; Save digit at r7-7");
    asm("        glo     r7");
    asm("        smi     7");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("        glo     r8");
    asm("        str     rd");
    asm("");
    asm("        ; Zero TMP at r7-4..r7-1");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("        ldi     0");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        str     rd");
    asm("");
    asm("        ; Load base into r8.hi shifted left 2, counter in r8.lo");
    asm("        glo     rc");
    asm("        shl");
    asm("        shl");
    asm("        phi     r8");
    asm("        ldi     6");
    asm("        plo     r8");
    asm("");
    asm("mulloop:");
    asm("        ; TMP = TMP << 1");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("");
    asm("        ; Extract next base bit");
    asm("        ghi     r8");
    asm("        shl");
    asm("        phi     r8");
    asm("        lbnf    mul_skip");
    asm("");
    asm("        ; TMP = TMP + result");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        sex     ra");
    asm("        ldi     0");
    asm("        shr");
    asm("");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        adc");
    asm("        str     rd");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        sex     r2");
    asm("");
    asm("mul_skip:");
    asm("        dec     r8");
    asm("        glo     r8");
    asm("        lbnz    mulloop");
    asm("");
    asm("        ; result = TMP");
    asm("        glo     r7");
    asm("        smi     4");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        lda     rd");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        lda     rd");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        lda     rd");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     rd");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; result = result + digit");
    asm("        glo     r7");
    asm("        smi     7");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("        ldn     rd");
    asm("        str     r2");
    asm("");
    asm("        sex     r2");
    asm("        ldi     0");
    asm("        shr");
    asm("");
    asm("        ldn     ra");
    asm("        adc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        lbr     digitloop");
    asm("");
    asm("done:");
    asm("        ; Store rf to end-pointer location if non-zero");
    asm("        glo     r7");
    asm("        smi     6");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ldn     rd");
    asm("        plo     ra");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        phi     ra");
    asm("");
    asm("        glo     ra");
    asm("        lbnz    write_endp");
    asm("        ghi     ra");
    asm("        lbz     rtn_done");
    asm("");
    asm("write_endp:");
    asm("        glo     rf");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ghi     rf");
    asm("        str     ra");
    asm("");
    asm("rtn_done:");

    return n;
}
