#define _ELFCLIB_
#include <mathu32.h>

uint32_t atou32(const char *nptr)
{
    uint32_t n;

    asm("; CDP1802 Assembly: decimal ASCII string to unsigned 32-bit integer");
    asm("; Compiler runtime version");
    asm(";");
    asm("; Memory layout:");
    asm(";   rb+1 .. rb+2  16-bit pointer to input string (little-endian)");
    asm(";   r7+1 .. r7+4  32-bit unsigned output integer (little-endian)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte before LSB of string pointer");
    asm(";   r7 = pointer to byte before LSB of output integer");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   [r7+1..r7+4] = parsed unsigned 32-bit integer");
    asm(";");
    asm("; Registers:");
    asm(";   rf      input string pointer");
    asm(";   ra      pointer to output integer LSB (r7+1)");
    asm(";   rc      scratch (multiply)");
    asm(";   rd      pointer to TMP LSB (r7-3)");
    asm(";   r8      scratch pointer");
    asm("");
    asm("atou32:");
    asm("        ; Load input string pointer into rf");
    asm("        copy    rb, r8");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        plo     rf");
    asm("        inc     r8");
    asm("        ldn     r8");
    asm("        phi     rf");
    asm("");
    asm("        ; ra = r7+1");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; rd = r7-3 → TMP LSB");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Zero output integer");
    asm("        ldi     0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        str     ra");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; Skip leading whitespace");
    asm("skipws:");
    asm("        ldn     rf");
    asm("        xri     020h");
    asm("        lbz     skipws_adv");
    asm("        ldn     rf");
    asm("        xri     009h");
    asm("        lbnz    chkplus");
    asm("skipws_adv:");
    asm("        inc     rf");
    asm("        lbr     skipws");
    asm("");
    asm("        ; Allow optional '+' prefix");
    asm("chkplus:");
    asm("        ldn     rf");
    asm("        xri     02bh");
    asm("        lbnz    digitloop");
    asm("        inc     rf");
    asm("");
    asm("digitloop:");
    asm("        ldn     rf");
    asm("        smi     030h            ; D = c - '0'");
    asm("        lbnf    done            ; < '0': stop");
    asm("        smi     00ah            ; D = c - '0' - 10");
    asm("        lbdf    done            ; >= 10: stop");
    asm("        adi     00ah            ; restore digit (0-9)");
    asm("        str     r2");
    asm("        inc     rf");
    asm("");
    asm("        ; result = result * 10 + digit");
    asm("");
    asm("        ; Step 1: copy result → TMP");
    asm("        lda     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        lda     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        lda     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     ra");
    asm("        str     rd");
    asm("");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 2: result = result << 1 (×2)");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        shlc");
    asm("        str     ra");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        ; Step 3: TMP = TMP << 1 (×2)");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 4: TMP = TMP << 1 (×4)");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 5: TMP = TMP << 1 (×8)");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ldn     rd");
    asm("        shlc");
    asm("        str     rd");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 6: result = result + TMP (×2 + ×8 = ×10)");
    asm("        sex     rd");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     ra");
    asm("        adc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        inc     rd");
    asm("        ldn     ra");
    asm("        adc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        inc     rd");
    asm("        ldn     ra");
    asm("        adc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        inc     rd");
    asm("        ldn     ra");
    asm("        adc");
    asm("        str     ra");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("        glo     r7");
    asm("        smi     3");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        smbi    0");
    asm("        phi     rd");
    asm("");
    asm("        ; Step 7: result = result + digit");
    asm("        sex     r2");
    asm("        ldi     0");
    asm("        shr");
    asm("        ldn     ra");
    asm("        adc");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        inc     ra");
    asm("        ldn     ra");
    asm("        adci    0");
    asm("        str     ra");
    asm("        copy    r7, ra");
    asm("        inc     ra");
    asm("");
    asm("        lbr     digitloop");
    asm("");
    asm("done:");

    return n;
}
