#define _ELFCLIB_
#include <mathu32.h>

int cmpu32(uint32_t a, uint32_t b)
{
    int r;

    asm("; CDP1802 Assembly: compare two 32-bit unsigned numbers, compiler runtime");
    asm(";");
    asm("; Memory layout at rb+1:");
    asm(";   rb+1 .. rb+4  a (4 bytes, LSB first)");
    asm(";   rb+5 .. rb+8  b (4 bytes, LSB first)");
    asm(";");
    asm("; Entry:");
    asm(";   rb = pointer to byte immediately before LSB of a");
    asm(";   r7 = pointer to byte immediately before result LSB");
    asm(";");
    asm("; Exit:");
    asm(";   rb, r7 preserved");
    asm(";   [r7+1..r7+2] = 0x0000 if a == b");
    asm(";                  0x0001 if a >  b");
    asm(";                  0xFFFF if a <  b  (16-bit signed -1)");
    asm(";");
    asm("; Registers: r8, ra, rc, rd, rf");
    asm(";   ra      result accumulator (0, then inc=+1 or dec=-1)");
    asm(";   rc.lo   equality OR accumulator");
    asm(";   rd      walks through a during subtraction");
    asm(";   rf      walks through b during subtraction");
    asm("");
    asm("ucmp32:");
    asm("        ; Initialize result accumulator ra = 0");
    asm("        ldi     0");
    asm("        plo     ra");
    asm("        phi     ra");
    asm("");
    asm("        ; rd = rb+1 → a LSB");
    asm("        copy    rb, rd");
    asm("        inc     rd");
    asm("");
    asm("        ; rf = rb+5 → b LSB");
    asm("        glo     rb");
    asm("        adi     5");
    asm("        plo     rf");
    asm("        ghi     rb");
    asm("        adci    0");
    asm("        phi     rf");
    asm("");
    asm("        ldi     0");
    asm("        plo     rc              ; equality OR = 0");
    asm("");
    asm("        sex     rf");
    asm("");
    asm("        lda     rd");
    asm("        sm                      ; a[0] - b[0]");
    asm("        plo     rc");
    asm("        inc     rf");
    asm("");
    asm("        lda     rd");
    asm("        smb                     ; a[1] - b[1] - borrow");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sex     r2");
    asm("        or");
    asm("        plo     rc");
    asm("        sex     rf");
    asm("        inc     rf");
    asm("");
    asm("        lda     rd");
    asm("        smb                     ; a[2] - b[2] - borrow");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sex     r2");
    asm("        or");
    asm("        plo     rc");
    asm("        sex     rf");
    asm("        inc     rf");
    asm("");
    asm("        ldn     rd");
    asm("        smb                     ; a[3] - b[3] - borrow, final DF");
    asm("        str     r2");
    asm("        glo     rc");
    asm("        sex     r2");
    asm("        or                      ; final equality OR");
    asm("        sex     r2");
    asm("");
    asm("        lbz     store           ; all differences zero: a == b, ra stays 0");
    asm("        lbnf    ret_neg         ; borrow: a < b");
    asm("");
    asm("        inc     ra              ; no borrow, nonzero: a > b → ra = 0x0001");
    asm("        lbr     store");
    asm("");
    asm("ret_neg:");
    asm("        dec     ra              ; ra = 0xFFFF");
    asm("");
    asm("store:");
    asm("        ; Write ra as 16-bit little-endian to r7+1..r7+2");
    asm("        glo     r7");
    asm("        adi     1");
    asm("        plo     rd");
    asm("        ghi     r7");
    asm("        adci    0");
    asm("        phi     rd");
    asm("");
    asm("        glo     ra");
    asm("        str     rd");
    asm("        inc     rd");
    asm("        ghi     ra");
    asm("        str     rd");

    return r;
}
